### ISSUE TITLE
User is Typing pushes all messages up

### ISSUE THREAD

**Issue by Hi-ImKyle** [refact0r/system24#9]
I know it's such a small thing. But maybe it would be better fit to put the text for when users are typing on the border at the bottom rather than just pushing messages up?

How it is at the moment
![image](https://github.com/user-attachments/assets/22e4f525-9a6f-45a7-9985-03421c846875)

How I am thinking it could be. Without it pushing messages
![image](https://github.com/user-attachments/assets/257e0dc4-364b-434e-8b35-700833b1ed52)

Just a small suggestion. Feel free to suggest other alternatives. I just don't think pushing messages up is good for readability. Particularly in lively channels

**Comment by refact0r** [comment]
i dislike how that looks, it gets too close to the "input" text.
honestly i don't find it that annoying, but the possible solutions are:

- have some permanent background there so the messages dont move
- somehow overlay the typing bar on top of the messages instead of pushing them up
- have an animation for when the typing bar comes in

**Comment by refact0r** [comment]
ok please check if this solution works. i made the typing bar overlay, so the chat shouldn't jump anymore.

**Comment by Hi-ImKyle** [comment]
Yep. Chat doesn't jump anymore 👍
